#äº®æš—æ¨¡å¼  å¯é€‰ light | dark | auto | time
mode: auto
# é¦–é¡µçš„å‚ç›´äº¤é”™æ’åˆ—æ–‡å­—æ•ˆæœ
banner:
  #æ˜¯å¦å¼€å¯
  enable: true
  #è®¾ç½®æ–‡å­—å†…å®¹
  title: 'çˆ±é˜…æ¸´çš„å›å¿†å½•'
  # æ˜¯å¦å¼€å¯æ ‡è¯­ä¸­å­—ç¬¦çš„å·¦å³è¾¹æ¡†
  border: true
  # åœ¨é¦–é¡µä¸‹æ–¹æ˜¾ç¤ºæµåŠ¨çš„äº‘
  cloud:
    # æ˜¯å¦å¼€å¯
    enable: false
    # è‡ªå®šä¹‰è‰²å½©
    color: "red"
    #  å‘ä¸‹ç®­å¤´æŒ‰é’®ï¼ˆç‚¹å‡»ç¿»é¡µï¼‰
    go_down:
      enable: true
      icon: icon-arrow-down-s-line
# å…¬å‘Š æ˜¾ç¤ºåœ¨æ‰€æœ‰æ–‡ç« å¡ç‰‡çš„æœ€ä¸Šæ–¹ï¼Œæ ‡è¯­çš„ä¸‹æ–¹ã€‚
notice:
  enable: false
  content: 'è¿˜æ²¡æƒ³å¥½'
# å¤´åƒ
avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  # å¤´åƒè¾¹ä¸Šçš„çŠ¶æ€
  status:
    enable: false
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šç­
# èƒŒæ™¯å›¾
bg_image:
  enable: true
  url: /blog.yuekelove/images/background.jpg
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8
# æœç´¢æ¡†
search:
  modal: true
  bg_image: /blog.yuekelove/images/background.jpg
  #dark_bg_image: xxx
  # placeholder:
# é¼ æ ‡ç‚¹å‡»çš„çƒŸèŠ±æ•ˆæœ
fireworks:
  enable: true
  colors:
    # è“
    - "158, 178, 203"
    # é»„
    - "230, 166, 8"
    # ç»¿
    - "138, 138, 43"
# é¦–é¡µå¡ç‰‡ä¸æ–‡ç« å†…éƒ¨å›¾ç‰‡çš„æ»šåŠ¨æµ®ç°æ•ˆæœ
scrollreveal:
  enable: false
  targets:
    - .post-card
    - .markdown-body img
# æ›¿æ¢é¼ æ ‡å…‰æ ‡ï¼Œé»˜è®¤å…³é—­
cursor:
  enable: false
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur
# ä¾§è¾¹æ  èƒŒæ™¯ä¸æ ‡ç­¾
#sidebar:
#  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
#  bg_position: bottom 3rem center
#  tagcloud:
#    enable: true
#    amount: 20

#reward:
#  enable: true
#  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
#  methods:
#    - name: æ”¯ä»˜å®
#      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/alipay-qrcode.jpg
#      color: "#00A3EE"
#      icon: icon-alipay-line
#    - name: QQ æ”¯ä»˜
#      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/qqpay-qrcode.png
#      color: "#12B7F5"
#      icon: icon-qq-line
#    - name: å¾®ä¿¡æ”¯ä»˜
#      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/wechatpay-qrcode.jpg
#      color: "#2DC100"
#      icon: icon-wechat-pay-line
#
#comment:
#  candidates:
#    - waline
#    # - giscus
#  tips:
#    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚
#
#waline:
#  enable: true
#  serverURL: https://waline.yunyoujun.cn
#  visitor: true
#  comment: true
#  emoji:
#    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
#    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
#    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/qq/
#  locale:
#    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
#  requiredMeta: ["nick"]
#
#github_issues:
#  enable: false
#
#github_discussions:
#  enable: false
#
#disqusjs:
#  enable: false
#  shortname: yunyoujun
#  apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN
#
## https://github.com/laymonage/giscus
#giscus:
#  enable: false
#  repo: YunYouJun/yunyoujun.github.io
#  repo-id:
#  category-id:
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light
#
#footer:
#  since: 2016
#  icon:
#    url: https://sponsors.yunyoujun.cn
#    title: äº‘æ¸¸å›çš„èµåŠ©è€…ä»¬
#  beian:
#    enable: true
#    icp: è‹ICPå¤‡17038157å·
#  support:
#    enable: true
#    title: åˆæ‹äº‘
#    link: https://www.upyun.com
#    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
#    prefix: æœ¬ç½‘ç«™ç”±
#    suffix: æä¾› CDN åŠ é€Ÿ
#  custom_text:
#
#engine_search:
#  enable: false
#
## If you want to use it, you need config algolia appID in _config.yml!!!
## https://github.com/oncletom/hexo-algolia
#algolia_search:
#  enable: true
#  # ...
#
#google_analytics:
#  enable: true
#  id: G-1LL0D86CY9
#
#google_adsense:
#  enable: true
#  client: ca-pub-2245427233262012
#
#post_edit:
#  enable: true
#  url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/
#
#albums:
#  enable: true
#
#girls:
#  enable: true
#
#tags:
#  åŠ¨ç”»: crimson
#  æ¼«ç”»: orange
#  Parcel: "#21374b"
#  å­¦ä¹ : saddlebrown
#  MAD: crimson
#  æ•™ç¨‹: royalblue
#  ç¬”è®°: dimgray
#  åˆ†äº«: "#0078e7"
#  éšç¬”: mediumpurple
#  Blender: "#d04d2d"
#  Linux: "#2577b1"
#  ä¸­ä¼ : "#ccb44b"
#  éƒ¨è½: "#DD306A"
#  ç§‘å¹»: midnightblue
#  èš‚èšæ£®æ—: "#54a892"
#
#categories:
#  äº‘æ¸¸çš„å°è§†é¢‘: "#FB7299"
#
#pages:
#  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
#    url: /links/
#    icon: icon-genderless-line
#    color: dodgerblue
#  - name: å–œæ¬¢çš„å¥³å­©å­
#    url: /girls/
#    icon: icon-women-line
#    color: hotpink
#
#menu:
#  custom:
#    title: ç•™è¨€æ¿
#    path: /about/#comment
#    icon: icon-clipboard-line
#
#
#baidu_push: true
#
#google_tagmanager:
#  enable: true
#  id: GTM-M9KWR9L
#
#wordcount:
#  enable: true
#
#say:
#  api: https://el-bot-api.vercel.app/api/words/young
#  hitokoto:
#    enable: false
#
#social:
#  - name: RSS
#    # set rss in your root config
#    # https://github.com/hexojs/hexo-generator-feed
#    link: /atom.xml # config.feed.path
#    icon: icon-rss-line
#    color: orange
#  - name: QQ ç¾¤ 1050458482
#    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
#    link: https://qm.qq.com/cgi-bin/qm/qr?k=kZJzggTTCf4SpvEQ8lXWoi5ZjhAx0ILZ&jump_from=webapi
#    icon: icon-qq-line
#    color: "#12B7F5"
#  - name: GitHub
#    link: https://github.com/YunYouJun
#    icon: icon-github-line
#    color: "#6e5494"
#  - name: å¾®åš
#    link: https://weibo.com/jizhideyunyoujun
#    icon: icon-weibo-line
#    color: "#E6162D"
#  - name: è±†ç“£
#    link: https://www.douban.com/people/yunyoujun/
#    icon: icon-douban-line
#    color: "#007722"
#  - name: ç½‘æ˜“äº‘éŸ³ä¹
#    link: https://music.163.com/#/user/home?id=247102977
#    icon: icon-netease-cloud-music-line
#    color: "#C20C0C"
#  - name: çŸ¥ä¹
#    link: https://www.zhihu.com/people/yunyoujun/
#    icon: icon-zhihu-line
#    color: "#0084FF"
#  - name: å“”å“©å“”å“©
#    link: https://space.bilibili.com/1579790
#    icon: icon-bilibili-line
#    color: "#FF8EB3"
#  - name: å¾®ä¿¡å…¬ä¼—å·
#    link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
#    icon: icon-wechat-2-line
#    color: "#1AAD19"
#  - name: Twitter
#    link: https://twitter.com/YunYouJun
#    icon: icon-twitter-line
#    color: "#1da1f2"
#  # - name: Telegram
#  #   link: https://t.me/yunyoujun_group
#  #   icon: icon-telegram-line
#  #   color: "#0088CC"
#  - name: Telegram Channel
#    link: https://t.me/elpsycn
#    # icon: icon-telegram-fill
#    icon: icon-telegram-line
#    color: "#0088CC"
#  - name: E-Mail
#    link: mailto:me@yunyoujun.cn
#    icon: icon-mail-line
#    color: "#8E71C1"
#  - name: Travelling
#    link: https://travellings.link
#    icon: icon-train-line
#    color: black
# pjax:
#   enable: true
